# Generated by Django 5.0.1 on 2025-09-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='off', max_length=10)),
                ('campaign_type', models.CharField(max_length=50)),
                ('metric_1_label', models.CharField(max_length=100)),
                ('metric_1_value', models.CharField(max_length=50)),
                ('metric_2_label', models.CharField(max_length=100)),
                ('metric_2_value', models.CharField(max_length=50)),
                ('metric_3_label', models.CharField(max_length=100)),
                ('metric_3_value', models.CharField(max_length=50)),
                ('spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='campaigns/')),
            ],
        ),
    ]
