# Generated by Django 5.0.1 on 2025-09-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrepoting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_type',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='metric_1_label',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='metric_1_value',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='metric_2_label',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='metric_2_value',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='metric_3_label',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='metric_3_value',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='url',
        ),
        migrations.AddField(
            model_name='campaign',
            name='messaging_conversations_started',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
