# Generated by Django 5.0.1 on 2024-07-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='today_visit',
            options={'verbose_name_plural': '1. Today Visit'},
        ),
        migrations.AlterField(
            model_name='today_visit',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
