# Generated by Django 5.0.1 on 2024-11-10 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_company_about'),
        ('utility', '0004_city_locality'),
        ('visit', '0004_rename_category_today_visit_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='today_visit',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='today_visit',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='today_visit',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.city'),
        ),
        migrations.AddField(
            model_name='today_visit',
            name='followup_meeting',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='today_visit',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.locality'),
        ),
        migrations.AddField(
            model_name='today_visit',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.call_status'),
        ),
    ]
