# Generated by Django 5.0.1 on 2024-11-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0005_remove_today_visit_contact_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='today_visit',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='today_visit',
            name='meet_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
