# Generated by Django 5.0.1 on 2024-11-10 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0006_today_visit_contact_no_today_visit_meet_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '2. Follow_Up',
            },
        ),
        migrations.AddField(
            model_name='today_visit',
            name='visit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.visit_type'),
        ),
    ]
