# Generated by Django 5.0.1 on 2024-12-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0007_visit_type_today_visit_visit_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit_type',
            options={'verbose_name_plural': '4. Visit_Type'},
        ),
    ]
