# Generated by Django 5.0.1 on 2025-04-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0009_alter_today_visit_city_alter_today_visit_locality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='today_visit',
            old_name='city',
            new_name='locality_city',
        ),
        migrations.RemoveField(
            model_name='today_visit',
            name='locality',
        ),
    ]
