# Generated by Django 5.0.1 on 2025-09-10 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0005_alter_category_description'),
        ('utility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_persone', models.CharField(blank=True, max_length=500, null=True)),
                ('business_name', models.CharField(blank=True, max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('business_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses_created', to=settings.AUTH_USER_MODEL)),
                ('locality_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.locality')),
                ('requirement_types', models.ManyToManyField(blank=True, related_name='meetings', to='utility.requirementtype')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.call_status')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '1. Response',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField(blank=True, null=True, verbose_name='Meeting Date & Time')),
                ('status', models.CharField(choices=[('not_fixed', 'Not Fixed'), ('fixed', 'Fixed'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='not_fixed', max_length=20, verbose_name='Meeting Status')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='response.response')),
            ],
            options={
                'verbose_name_plural': '2. Meeting',
            },
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup', models.DateTimeField(blank=True, null=True)),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='response.response')),
            ],
            options={
                'verbose_name_plural': '3.Follow_Up',
            },
        ),
    ]
