# Generated by Django 5.0.1 on 2025-08-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='contact_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
