# Generated by Django 5.0.1 on 2025-12-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='locality_city',
            new_name='locality',
        ),
    ]
