# Generated by Django 5.0.1 on 2025-09-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('New Meeting', 'New Meeting'), ('fixed', 'Fixed'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='not_fixed', max_length=20, verbose_name='Meeting Status'),
        ),
    ]
