# Generated by Django 5.0.1 on 2025-08-06 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_category_status'),
        ('response', '0001_initial'),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting_follow_up',
            name='business_category',
        ),
        migrations.RemoveField(
            model_name='meeting_follow_up',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='meeting_follow_up',
            name='contact_persone',
        ),
        migrations.RemoveField(
            model_name='meeting_follow_up',
            name='response_status',
        ),
        migrations.RemoveField(
            model_name='meeting_follow_up',
            name='type',
        ),
        migrations.AddField(
            model_name='response',
            name='Meeting_follow_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='business_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.category'),
        ),
        migrations.AddField(
            model_name='response',
            name='business_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='contact_persone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='response_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.response_status'),
        ),
    ]
