# Generated by Django 5.0.1 on 2025-08-06 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_remove_meeting_follow_up_business_category_and_more'),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting_follow_up',
            name='requirement_type',
        ),
        migrations.AddField(
            model_name='response',
            name='requirement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.requirementtype'),
        ),
    ]
