# Generated by Django 5.0.1 on 2025-09-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_alter_meeting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='contact_no',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
