# Generated by Django 5.0.1 on 2025-08-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0003_alter_response_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
