# Generated by Django 5.0.1 on 2025-09-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0003_alter_response_contact_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='followup',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_date',
        ),
        migrations.AddField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('New ', 'New '), ('2ND TIME', '2ND TIME'), ('HOT', 'HOT'), ('COOL', 'COOL')], default='New Followup', max_length=25, verbose_name='Followup Status'),
        ),
        migrations.AddField(
            model_name='response',
            name='meeting_follow',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Meeting Date & Time'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('New Meeting', 'New Meeting'), ('Deal Done', 'Deal Done'), ('Re Meeting', 'Re Meeting'), ('cancelled', 'Cancelled')], default='New Meeting', max_length=25, verbose_name='Meeting Status'),
        ),
    ]
