# Generated by Django 5.0.1 on 2024-09-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0003_follow_up_city_follow_up_locality_meeting_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='meeting_follow_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
