# Generated by Django 5.0.1 on 2025-09-10 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0004_rename_call_status_response_status_and_more'),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='city',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='locality_city',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='city',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='locality_city',
        ),
        migrations.AddField(
            model_name='response',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.city'),
        ),
        migrations.AddField(
            model_name='response',
            name='locality_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.locality'),
        ),
    ]
