# Generated by Django 5.0.1 on 2024-12-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0004_response_meeting_follow_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
