# Generated by Django 5.0.1 on 2025-09-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0004_remove_followup_followup_remove_meeting_meeting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('None ', 'None '), ('New ', 'New '), ('2ND TIME', '2ND TIME'), ('HOT', 'HOT'), ('COOL', 'COOL')], default='None', max_length=25, verbose_name='Followup Status'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('New Meeting', 'New Meeting'), ('Deal Done', 'Deal Done'), ('Re Meeting', 'Re Meeting'), ('cancelled', 'Cancelled')], default='None', max_length=25, verbose_name='Meeting Status'),
        ),
    ]
