# Generated by Django 5.0.1 on 2025-09-10 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_category_status'),
        ('response', '0005_remove_followup_city_remove_followup_locality_city_and_more'),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='business_category',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='requirement_types',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='response',
            name='business_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.category'),
        ),
        migrations.AddField(
            model_name='response',
            name='requirement_types',
            field=models.ManyToManyField(blank=True, related_name='meetings', to='utility.requirementtype'),
        ),
    ]
