# Generated by Django 5.0.1 on 2025-04-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0005_alter_response_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow_up',
            old_name='locality',
            new_name='locality_city',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='locality',
            new_name='locality_city',
        ),
        migrations.RemoveField(
            model_name='follow_up',
            name='city',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='city',
        ),
    ]
