# Generated by Django 5.0.1 on 2025-09-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0005_alter_followup_status_alter_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='follow_up',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='featured_property',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('New ', 'New '), ('2ND TIME', '2ND TIME'), ('HOT', 'HOT'), ('COOL', 'COOL')], max_length=25, verbose_name='Followup Status'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('New Meeting', 'New Meeting'), ('Re Meeting', 'Re Meeting'), ('cancelled', 'Cancelled'), ('Deal Done', 'Deal Done')], max_length=25, verbose_name='Meeting Status'),
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('Follow_Up', 'Follow_Up'), ('Software_company', 'Software Company'), ('For_job', 'For Job'), ('Training', 'Training'), ('Fake_lead', 'face Lead'), ('Deal_close', 'Deal Close')], default='New', max_length=25, verbose_name='Response Status'),
        ),
    ]
