# Generated by Django 5.0.1 on 2025-09-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0006_followup_follow_up_meeting_featured_property_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup',
            options={'verbose_name_plural': '3. Follow Up'},
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='follow_up',
            new_name='featured_property',
        ),
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('New Meeting', 'New Meeting'), ('Re Meeting', 'Re Meeting'), ('cancelled', 'Cancelled'), ('Deal Done', 'Deal Done')], max_length=25, verbose_name='Meeting Status'),
        ),
    ]
