# Generated by Django 5.0.1 on 2025-09-10 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0006_remove_meeting_business_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='business_category',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='description',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='requirement_types',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='updated_by',
        ),
    ]
