# Generated by Django 5.0.1 on 2025-04-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0006_rename_locality_follow_up_locality_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='locality',
            new_name='locality_city',
        ),
        migrations.RemoveField(
            model_name='response',
            name='city',
        ),
    ]
