# Generated by Django 5.0.1 on 2025-09-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0007_remove_followup_business_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='meeting_followup',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
