# Generated by Django 5.0.1 on 2025-09-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0007_alter_followup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('Follow_Up', 'Follow_Up'), ('Not_received', 'Not Received'), ('Software_company', 'Software Company'), ('For_job', 'For Job'), ('Training', 'Training'), ('Fake_lead', 'face Lead'), ('Deal_close', 'Deal Close')], default='New', max_length=25, verbose_name='Response Status'),
        ),
    ]
