# Generated by Django 5.0.1 on 2025-08-05 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_company_sub_locality'),
        ('response', '0007_rename_locality_response_locality_city_and_more'),
        ('utility', '0007_response_from_response_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='locality_city',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='name',
        ),
        migrations.RemoveField(
            model_name='response',
            name='response_from',
        ),
        migrations.RemoveField(
            model_name='response',
            name='response_status',
        ),
        migrations.RemoveField(
            model_name='response',
            name='call_comment',
        ),
        migrations.RemoveField(
            model_name='response',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='response',
            name='locality_city',
        ),
        migrations.RemoveField(
            model_name='response',
            name='meeting_follow_up',
        ),
        migrations.RemoveField(
            model_name='response',
            name='name',
        ),
        migrations.AddField(
            model_name='response',
            name='call_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.response_status'),
        ),
        migrations.AddField(
            model_name='response',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Meeting_Follow_Up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Meeting', 'Meeting'), ('Follow_Up', 'Follow_Up')], max_length=25, null=True)),
                ('Meeting_follow_up', models.DateTimeField(blank=True, null=True)),
                ('contact_porsone', models.CharField(blank=True, max_length=500, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=255, null=True)),
                ('business_name', models.CharField(blank=True, max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('business_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.city')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meeting_followups', to=settings.AUTH_USER_MODEL)),
                ('locality_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.locality')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='response.response')),
                ('response_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.response_status')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_meeting_followups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '2. Meeting Follow_Up',
            },
        ),
        migrations.DeleteModel(
            name='Follow_Up',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
        migrations.DeleteModel(
            name='Response_From',
        ),
        migrations.DeleteModel(
            name='Response_Status',
        ),
    ]
