# Generated by Django 5.0.1 on 2025-09-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0008_response_meeting_followup_alter_meeting_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting',
            field=models.CharField(choices=[('Meeting_Done', 'Meeting_Done'), ('fixed', 'Fixed'), ('cancelled', 'Cancelled')], default='Fixed', max_length=20, verbose_name='Meeting Status'),
        ),
    ]
