# Generated by Django 5.0.1 on 2025-08-05 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0009_alter_meeting_follow_up_created_by_and_more'),
        ('utility', '0007_response_from_response_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_follow_up',
            name='response_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.response_status'),
        ),
        migrations.AlterField(
            model_name='response',
            name='call_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.call_status'),
        ),
    ]
