# Generated by Django 5.0.1 on 2025-09-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0009_alter_meeting_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='meeting_followup',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
