# Generated by Django 5.0.1 on 2025-10-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0009_lead_productservice_sale_staff_lead_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='products',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.DeleteModel(
            name='ProductService',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
