# Generated by Django 5.0.1 on 2025-10-10 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0010_remove_lead_assigned_to_remove_sale_lead_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='featured_property',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='featured_property',
        ),
        migrations.RemoveField(
            model_name='response',
            name='meeting_follow',
        ),
        migrations.AddField(
            model_name='followup',
            name='follow',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Followup Date & Time'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Meeting Date & Time'),
        ),
        migrations.AddField(
            model_name='response',
            name='voice_recording',
            field=models.FileField(blank=True, null=True, upload_to='call_recordings/'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('New followup', 'New followup'), ('Re followup', 'Re followup'), ('cancelled', 'Cancelled'), ('Deal Done', 'Deal Done')], max_length=25, verbose_name='Meeting Status'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='response.staff'),
        ),
        migrations.AddField(
            model_name='response',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='response.staff'),
        ),
    ]
