# Generated by Django 5.0.1 on 2025-08-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0010_alter_meeting_follow_up_response_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting_follow_up',
            old_name='contact_porsone',
            new_name='contact_persone',
        ),
    ]
