# Generated by Django 5.0.1 on 2025-09-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0010_remove_response_meeting_followup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('not_fixed', 'Not Fixed'), ('fixed', 'Fixed'), ('cancelled', 'Cancelled')], default='not_fixed', max_length=20, verbose_name='Meeting Status'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Meeting Date & Time'),
        ),
    ]
