# Generated by Django 5.0.1 on 2025-09-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0011_meeting_status_alter_meeting_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='meeting',
            new_name='meeting_date',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('not_fixed', 'Not Fixed'), ('fixed', 'Fixed'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='not_fixed', max_length=20, verbose_name='Meeting Status'),
        ),
    ]
