# Generated by Django 5.0.1 on 2025-10-11 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0012_alter_meeting_options_alter_response_options_and_more'),
        ('utility', '0005_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='business_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.category'),
        ),
    ]
