# Generated by Django 5.0.1 on 2025-10-13 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0013_alter_response_business_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voicerecording',
            options={},
        ),
        migrations.AlterField(
            model_name='voicerecording',
            name='file',
            field=models.FileField(upload_to='voice_recordings/'),
        ),
        migrations.AlterField(
            model_name='voicerecording',
            name='note',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voicerecording',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='response.response'),
        ),
    ]
