# Generated by Django 5.0.1 on 2025-10-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0014_alter_voicerecording_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
