# Generated by Django 5.0.1 on 2025-12-25 05:00

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('response', '0001_initial'),
        ('utility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.city')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.locality')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('Follow_Up', 'Follow Up'), ('Not_received', 'Not Received'), ('Not Interested', 'Not Interested'), ('They Will Connect', 'They Will Connect'), ('Call later', 'Call later'), ('Call Tomorrow', 'Call Tomorrow'), ('Switched Off', 'Switched Off'), ('Invalid Number', 'Invalid Number')], default='New', max_length=25)),
                ('company_name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('google_map', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logo/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='response.staff')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_created', to=settings.AUTH_USER_MODEL)),
                ('googlemap_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.googlemap_status')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.locality')),
                ('sub_locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.sub_locality')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '1. Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_comments_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_comments_updated', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='business.company')),
            ],
            options={
                'verbose_name_plural': '3. Comments',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('error', models.CharField(max_length=500, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.company')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(blank=True, max_length=500)),
                ('answers', models.TextField(blank=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.company')),
            ],
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New Followup', 'New Followup'), ('Re Followup', 'Re Followup'), ('Cancelled', 'Cancelled'), ('Deal Done', 'Deal Done')], max_length=25, verbose_name='Followup Status')),
                ('followup_date', models.DateTimeField(blank=True, null=True, verbose_name='Followup Date & Time')),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_followup_assigned', to='response.staff')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='business.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_followup_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_followup_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '3. Followups',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.company')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New Meeting', 'New Meeting'), ('Re Meeting', 'Re Meeting'), ('Cancelled', 'Cancelled'), ('Deal Done', 'Deal Done')], max_length=25, verbose_name='Meeting Status')),
                ('meeting_date', models.DateTimeField(blank=True, null=True, verbose_name='Meeting Date & Time')),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_meeting_assigned', to='response.staff')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='business.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_meeting_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_meeting_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '2. Meetings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=50, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.company')),
                ('socia_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.socialsite')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_for', models.CharField(choices=[('Telling Meeting', 'Telling Meeting'), ('Door To Door', 'Door To Door'), ('Site Visit', 'Site Visit'), ('Follow Up', 'Follow Up'), ('Negotiation', 'Negotiation')], max_length=50)),
                ('visit_type', models.CharField(choices=[('1st Visit', '1st Visit'), ('2nd Visit', '2nd Visit'), ('3rd Visit', '3rd Visit'), ('4th Visit', '4th Visit'), ('5th Visit', '5th Visit'), ('6th Visit', '6th Visit'), ('7th Visit', '7th Visit'), ('8th Visit', '8th Visit'), ('9th Visit', '9th Visit'), ('10th Visit', '10th Visit')], max_length=50)),
                ('visit_status', models.CharField(choices=[('Deal_Close', 'Deal Close'), ('Meeting', 'Meeting'), ('Follow_Up', 'Follow Up'), ('Owner not In Office', 'Owner not In Office'), ('Interested', 'Interested'), ('Not Interested', 'Not Interested')], max_length=50)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='business.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '5. Visits',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='call_recordings/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to='business.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_voice_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '4. Voice Recordings',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
