# Generated by Django 5.0.1 on 2025-12-25 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='whatsapp',
        ),
    ]
