# Generated by Django 5.0.1 on 2024-06-08 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approx',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approx',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.city'),
        ),
        migrations.AlterField(
            model_name='approx',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.locality'),
        ),
    ]
