# Generated by Django 5.0.1 on 2025-08-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_remove_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
    ]
