# Generated by Django 5.0.1 on 2025-12-25 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_remove_company_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
    ]
