# Generated by Django 5.0.1 on 2024-06-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_company_googlemap_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
