# Generated by Django 5.0.1 on 2025-08-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
