# Generated by Django 5.0.1 on 2025-12-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_company_email_company_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='google_map',
        ),
        migrations.RemoveField(
            model_name='company',
            name='googlemap_status',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='company',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='company',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='company',
            name='total_reviews',
        ),
        migrations.RemoveField(
            model_name='company',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
        migrations.RemoveField(
            model_name='company',
            name='whatsapp',
        ),
    ]
