# Generated by Django 5.0.1 on 2025-10-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='sub_locality',
        ),
        migrations.AlterField(
            model_name='company',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
