# Generated by Django 5.0.1 on 2025-12-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_remove_company_created_by_remove_company_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_verified',
        ),
    ]
