# Generated by Django 4.2 on 2024-06-09 07:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
