# Generated by Django 5.0.1 on 2025-10-11 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_remove_company_sub_locality_alter_company_create_at_and_more'),
        ('response', '0013_alter_response_business_category'),
        ('utility', '0005_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approx',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.category'),
        ),
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.category'),
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-create_at'], 'verbose_name_plural': '1. Company'},
        ),
        migrations.AlterModelOptions(
            name='follow_up',
            options={'ordering': ['-follow_up'], 'verbose_name_plural': '2. Follow_Up'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-meeting'], 'verbose_name_plural': '3. Meeting'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-visit_date'], 'verbose_name_plural': '4. Visit'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='about',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='keywords',
        ),
        migrations.AddField(
            model_name='company',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='response.staff'),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images/'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='business.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_comments_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_comments_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '3. Comments',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='call_recordings/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to='business.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_voice_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '4. Voice Recordings',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
