# Generated by Django 5.0.1 on 2025-12-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_company_created_by_company_email_company_google_map_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
    ]
