# Generated by Django 5.0.1 on 2025-10-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_approx_category_alter_company_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
