# Generated by Django 5.0.1 on 2025-01-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='call_comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='followup_meeting',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
