# Generated by Django 5.0.1 on 2025-12-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_remove_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/logo/'),
        ),
    ]
