# Generated by Django 5.0.1 on 2025-10-12 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_delete_visit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_for', models.CharField(choices=[('Telling Meeting', 'Telling Meeting'), ('Door To Door', 'Door To Door'), ('Site Visit', 'Site Visit'), ('Follow Up', 'Follow Up'), ('Negotiation', 'Negotiation')], max_length=50)),
                ('visit_type', models.CharField(choices=[('1st Visit', '1st Visit'), ('2nd Visit', '2nd Visit'), ('3rd Visit', '3rd Visit'), ('4th Visit', '4th Visit'), ('5th Visit', '5th Visit'), ('6th Visit', '6th Visit'), ('7th Visit', '7th Visit'), ('8th Visit', '8th Visit'), ('9th Visit', '9th Visit'), ('10th Visit', '10th Visit')], max_length=50)),
                ('visit_status', models.CharField(choices=[('Deal_Close', 'Deal Close'), ('Meeting', 'Meeting'), ('Follow_Up', 'Follow Up'), ('Owner not In Office', 'Owner not In Office'), ('Interested', 'Interested'), ('Not Interested', 'Not Interested')], max_length=50)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='business.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '5. Visits',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
