# Generated by Django 5.0.1 on 2025-10-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='call_comment',
        ),
        migrations.RemoveField(
            model_name='company',
            name='call_status',
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('Follow_Up', 'Follow_Up'), ('Not_received', 'Not Received'), ('Not Interested', 'Not Interested'), ('They Will Connect', 'They Will Connect'), ('Call later', 'Call later'), ('Call Tomorrow', 'Call Tomorrow'), ('Switched Off', 'Switched Off'), ('Invalid Number Off', 'Invalid Number')], default='New', max_length=25, verbose_name='Company Status'),
        ),
    ]
