# Generated by Django 5.0.1 on 2025-04-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_remove_city_parent_remove_locality_city_and_more'),
        ('visit', '0009_alter_today_visit_city_alter_today_visit_locality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Locality',
        ),
    ]
