# Generated by Django 5.0.1 on 2025-10-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_remove_company_call_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicerecording',
            name='note',
        ),
    ]
