# Generated by Django 5.0.1 on 2025-10-22 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_remove_voicerecording_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='company',
        ),
        migrations.DeleteModel(
            name='Follow_Up',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
