# Generated by Django 5.0.1 on 2025-11-06 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_followup_meeting'),
        ('utility', '0008_sub_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sub_locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.sub_locality'),
        ),
    ]
