# Generated by Django 5.0.1 on 2025-11-12 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_company_sub_locality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='followup_meeting',
        ),
    ]
