# Generated by Django 5.0.1 on 2025-10-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.AddField(
            model_name='followup',
            name='voice_recording',
            field=models.FileField(blank=True, null=True, upload_to='call_recordings/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='google_calendar_token',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
