# Generated by Django 5.0.1 on 2025-10-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_lead_email_alter_lead_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, help_text='लीड कहाँ से आई? उदाहरण: वेबसाइट, कॉल, रेफरल', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
