# Generated by Django 5.0.1 on 2025-12-25 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='utility_category',
        ),
    ]
