# Generated by Django 5.0.1 on 2025-12-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_remove_category_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
