# Generated by Django 5.0.1 on 2025-10-11 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_remove_company_sub_locality_alter_company_create_at_and_more'),
        ('utility', '0002_remove_locality_city_remove_locality_create_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sub_Locality',
        ),
    ]
