# Generated by Django 4.2 on 2024-06-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_googlemap_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlemap_status',
            options={'verbose_name_plural': '4. Googlemap_Status'},
        ),
    ]
