# Generated by Django 5.0.1 on 2025-12-25 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_alter_category_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='update_at',
        ),
    ]
