# Generated by Django 5.0.1 on 2025-10-11 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_delete_sub_locality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locality',
            name='status',
        ),
    ]
