# Generated by Django 5.0.1 on 2025-12-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_remove_category_icon_alter_category_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category/icons/'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
