# Generated by Django 5.0.1 on 2025-04-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_city_locality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting_Followup_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
