# Generated by Django 5.0.1 on 2025-10-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
    ]
