# Generated by Django 5.0.1 on 2025-10-11 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0006_remove_category_description_remove_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.city'),
        ),
    ]
