# Generated by Django 5.0.1 on 2025-08-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0006_sub_locality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response_From',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '4. Response_From',
            },
        ),
        migrations.CreateModel(
            name='Response_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '5. Response_Status',
            },
        ),
    ]
