# Generated by Django 5.0.1 on 2025-12-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0008_sub_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category/icons/'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
